FPGAMMIX_DIR=/home/tommy/fpgammix
TARGET=fpgammix-sim

include ../include/rules.mk

#all: test-div-kernel.dis test-div-kernel.run-fpgammix-sim
#all: test-divu-kernel.run-fpgammix-sim test-divu-kernel.dis

run: test-$(WHAT)-kernel.run-$(TARGET)


